service: aws-lambda-crud-node-dev
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs14.x
  region: us-east-1
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:*
      Resource:
        -  arn:aws:dynamodb:us-east-1:616564708106:table/TaskTable

functions:
  createTask:
    handler: src/handler.addTaskHandler
    events:
      - httpApi:
          path: /tasks
          method: post
  listTasks:
    handler: src/handler.getTasksHandler
    events:
      - httpApi:
          path: /tasks
          method: get
  getTask:
    handler: src/handler.getTaskHandler
    events:
      - httpApi:
          path: /tasks/{id}
          method: get
  deleteTask:
    handler: src/handler.deleteTaskHandler
    events:
      - httpApi:
          path: /tasks/{id}
          method: delete
  updateTask:
    handler: src/handler.updateTaskHandler
    events:
      - httpApi:
          path: /tasks/{id}
          method: put

resources:
  Resources:
    TaskTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: TaskTable
        BillingMode: PAY_PER_REQUEST
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
